tweetapp/urls.py
from django.urls import path
from . import views
from .views import SignUpView


app_name='tweetapp'

urlpatterns = [
    path('',views.listtweets,name='listtweets'),
    path('showmytweet/',views.showmytweet,name='showmytweet'),
    path('addtweet/',views.addtweet,name='addtweet'),
    path("signup/", SignUpView.as_view(), name="signup"),
    path('deletemytweet/<int:id>',views.deletemytweet,name='deletemytweet'),
]

tweetyapp/urls.py
from django.contrib import admin
from django.urls import path , include

urlpatterns = [
    path("admin/", admin.site.urls),
    path("",include('tweetapp.urls')),
    path("",include('django.contrib.auth.urls')),
]

tweetapp/models.py
from django.db import models
from django.contrib.auth.models import User
# Create your models here.


class Tweet(models.Model):
    username=models.ForeignKey(User,on_delete=models.CASCADE,null=True)
    tweet=models.CharField(max_length=140)
    time=models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"username {self.username} , tweet {self.tweet} , time {self.time}"

tweetapp/views.py
from django.shortcuts import render,redirect
from . import models
from django.urls import reverse, reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.forms import UserCreationForm
from django.views import generic

# Create your views here.

def listtweets(request):
     tweets_list = models.Tweet.objects.all()
     dictionarytweet={"tweets":tweets_list}
     return render(request,"tweetapp/listtweets.html",context=dictionarytweet)

@login_required(login_url="/login")
def showmytweet(request):
    mytweets = models.Tweet.objects.filter(username=request.user).all()
    mytweetsdic = {"mytweets":mytweets}
    return render(request,'tweetapp/showmytweet.html',context=mytweetsdic)

@login_required(login_url="/login")
def addtweet(request):
    if request.POST:
        tweet= request.POST['tweet']
        models.Tweet.objects.create(username=request.user,tweet=tweet,time="")
        return redirect(reverse('tweetapp:listtweets'))
    else:
        return render(request,'tweetapp/addtweet.html')
    
@login_required
def deletemytweet(request, id):
    mytweet = models.Tweet.objects.get(pk=id)
    if request.user == mytweet.username:
        models.Tweet.objects.filter(id=id).delete()
        return(redirect('tweetapp:listtweets'))
    
    
class SignUpView(generic.CreateView):
    form_class = UserCreationForm
    success_url = reverse_lazy("login")
    template_name = "registration/signup.html"

templates/base.html
{% load static %}
<!doctype html>
<html>
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <link rel="stylesheet" href="{% static 'tweetapp/form.css' %}">
  <script src="https://cdn.tailwindcss.com"></script>
</head>
<body>
    <div class="min-h-full">
        <nav class="bg-gray-800">
          <div class="mx-auto max-w-7xl px-4 sm:px-6 lg:px-8">
            <div class="flex h-16 items-center justify-between">
              <div class="flex items-center">
                <div class="flex-shrink-0">
                  <p class="text-white text-xl">TWEET App</p>
                </div>
                <div class="hidden md:block">
                  <div class="ml-10 flex items-baseline space-x-4">
                    <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
                    <a href="{% url 'tweetapp:listtweets' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">All Tweets</a>
                    <a href="{% url 'tweetapp:showmytweet' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">My Tweets</a>
                    <a href="{% url 'tweetapp:addtweet' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Add Tweet</a>
                    <a href="{% url 'login' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Login</a>
                    {% if request.user.is_authenticated %}
                    <form action="{% url 'logout' %}" method="POST" id ="logout" class="nav-link">
                      {% csrf_token %}
                      <input class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium" type="submit" value="Logout">
                    </form>
                    {% else %}
                    <a href="{% url 'tweetapp:signup' %}" class="text-gray-300 hover:bg-gray-700 hover:text-white rounded-md px-3 py-2 text-sm font-medium">Sign up</a>
                    {% endif %}
                  </div>
                </div>
              </div>
            </div>
          </div>
          </div>
        </nav>
        {%block content%} 
        
        {%endblock%}
      </div>
      <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
        <p class="text-xl font-bold tracking-tight text-gray-900" style="opacity:0.2">Created by Hamza Ünsal<br>Github.com/neymaro</p>
      </div>
</body>
</html>

tweetapp/templates/tweetapp/addtweet.html
{% extends "base.html" %}

{%block content%} 
    <header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">Add Tweet</h1>
    </div>
  </header>
 <!--Add Tweet Part-->
 <form action="" method="POST" class="mt-4">
    {% csrf_token %} 
   <div class="max-w-2xl mx-auto">

     <label for="message" class="block mb-2 text-sm font-medium text-gray-900 dark:text-gray-400">Your Tweet</label>
     <textarea id="tweet" rows="4" name="tweet" maxlength="140" style="resize:none;"
    class="block p-2.5 w-full text-sm text-gray-900 bg-gray-50 rounded-lg border border-gray-300 focus:ring-blue-500 focus:border-blue-500 dark:bg-gray-700 dark:border-gray-600 dark:placeholder-gray-400 dark:text-white dark:focus:ring-blue-500 dark:focus:border-blue-500" 
    placeholder="Your tweet , max 140 character." ></textarea>
     <button
    class="middle none center mr-4 mt-5 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none"
    data-ripple-light="true">Tweet</button>
    </div>
  </form>

  {%endblock%}

tweetapp/templates/tweetapp/listtweets.html
{% extends "base.html" %}

{%block content%} 
<header class="bg-white shadow">
  <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
    <h1 class="text-3xl font-bold tracking-tight text-gray-900">All Tweets</h1>
  </div>
</header>
<main>
  <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
                <!-- component -->
    <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.4/dist/flowbite.min.css" />
    <!--Twitler-->
    {% for item in tweets %}
    <blockquote class="relative w-full bg-white p-5 border border-gray-200 break-inside-avoid-column m-5">
        <h2 class="text-lg">{{item.tweet}}</h2>
        <div class="mt-5 flex items-start gap-4">
            <img src="https://www.svgrepo.com/show/491978/gas-costs.svg" class="w-10 h-10 object-cover object-center" alt="Aaron Francis">
            <div class="text-m">
                <cite class="not-italic font-bold">@{{item.username}}</cite><br>
                <cite class="italic">{{item.time}}</cite>
            </div>
            
        </div>
    </blockquote>
    {% endfor %}
</main>
{%endblock%}

tweetapp/templates/tweetapp/showmytweet.html
{% extends "base.html" %}

{%block content%} 
<header class="bg-white shadow">
    <div class="mx-auto max-w-7xl px-4 py-6 sm:px-6 lg:px-8">
      <h1 class="text-3xl font-bold tracking-tight text-gray-900">My Tweets</h1>
    </div>
  </header>
  <main>
    <div class="mx-auto max-w-7xl py-6 sm:px-6 lg:px-8">
                  <!-- component -->
      <link rel="stylesheet" href="https://unpkg.com/flowbite@1.4.4/dist/flowbite.min.css" />
      <!--Twitler-->
      {% for item in mytweets %}
      <blockquote class="relative w-full bg-white p-5 border border-gray-200 break-inside-avoid-column m-5">
          <h2 class="text-lg">{{item.tweet}}</h2>
          <div class="mt-5 flex items-start gap-4">
              <img src="https://www.svgrepo.com/show/491978/gas-costs.svg" class="w-10 h-10 object-cover object-center" alt="Aaron Francis">
              <div class="text-m">
                  <cite class="not-italic font-bold">@{{item.username}}</cite><br>
                  <cite class="italic">{{item.time}}</cite>
                 <br><br><a href="{% url 'tweetapp:deletemytweet' id=item.id%}" 
                  class="middle none center  mr-4 rounded-lg bg-blue-500 py-3 px-6 font-sans text-xs font-bold uppercase text-white shadow-md shadow-blue-500/20 transition-all hover:shadow-lg hover:shadow-blue-500/40 focus:opacity-[0.85] focus:shadow-none active:opacity-[0.85] active:shadow-none disabled:pointer-events-none disabled:opacity-50 disabled:shadow-none">Delete</a>
              </div>
          </div>
      </blockquote>
      {% endfor %}
  </main>
  
{%endblock%}